/* The following code was generated by JFlex 1.7.0 */

import java_cup.runtime.*;
import java.lang.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>src/lexer/lexer.jflex</tt>
 */
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\67\1\2\1\30\1\30\1\1\22\0\1\60\1\66\1\31"+
    "\1\3\1\0\1\65\1\41\1\27\1\51\1\52\1\63\1\62\1\55"+
    "\1\4\1\15\1\64\1\6\1\10\6\14\2\5\1\56\1\57\1\46"+
    "\1\61\1\45\2\0\1\12\1\7\2\12\1\16\1\23\10\32\1\13"+
    "\4\32\1\17\3\32\1\11\2\32\1\47\1\0\1\50\1\43\1\32"+
    "\1\0\1\24\1\7\1\12\1\40\1\22\1\12\2\32\1\34\2\32"+
    "\1\25\1\32\1\37\1\36\2\32\1\20\1\26\1\35\1\21\1\32"+
    "\1\33\1\11\2\32\1\53\1\42\1\54\1\44\6\0\1\30\u1fa2\0"+
    "\1\30\1\30\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\2\6\1\7"+
    "\1\10\3\7\1\1\1\2\1\1\3\7\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\1\1\0\1\36\4\0\1\37"+
    "\4\7\1\0\1\40\1\0\1\40\1\7\1\41\1\7"+
    "\1\42\1\43\1\44\1\45\1\46\1\47\1\50\1\51"+
    "\1\52\1\53\1\54\1\55\1\0\1\37\3\6\3\7"+
    "\1\56\1\0\1\57\1\60\1\61\1\62\1\7\2\0"+
    "\1\63\2\0\1\64\1\65";

  private static int [] zzUnpackAction() {
    int [] result = new int[93];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\70\0\160\0\250\0\340\0\u0118\0\u0150\0\u0188"+
    "\0\u01c0\0\u01f8\0\u0230\0\u0268\0\u02a0\0\u02d8\0\70\0\u0310"+
    "\0\u0348\0\u0380\0\u03b8\0\70\0\70\0\70\0\70\0\u03f0"+
    "\0\u0428\0\70\0\70\0\70\0\70\0\70\0\70\0\70"+
    "\0\70\0\70\0\70\0\u0460\0\u0498\0\u04d0\0\u0508\0\u0540"+
    "\0\u0578\0\u01f8\0\70\0\u05b0\0\u05e8\0\u0620\0\u0658\0\u0690"+
    "\0\u06c8\0\u0700\0\u0738\0\u0770\0\u02d8\0\u02d8\0\u0310\0\u0310"+
    "\0\u07a8\0\u01c0\0\u07e0\0\70\0\70\0\70\0\70\0\70"+
    "\0\70\0\70\0\u0818\0\70\0\u0850\0\70\0\70\0\u0888"+
    "\0\u0888\0\u05e8\0\u0620\0\u0658\0\u08c0\0\u08f8\0\u0930\0\u01c0"+
    "\0\u0968\0\u09a0\0\70\0\70\0\u01c0\0\u09d8\0\u0a10\0\u0a48"+
    "\0\u01c0\0\u0a80\0\u0ab8\0\70\0\70";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[93];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\7\3\11\1\7\1\12\1\11\1\13\3\11\1\14"+
    "\1\15\2\11\1\16\1\17\1\20\2\11\1\21\1\11"+
    "\1\22\1\23\1\11\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\1\51\1\43\72\0\1\43\66\0\1\43\66\0\1\5"+
    "\2\0\65\5\5\0\2\7\1\0\1\7\3\0\1\7"+
    "\1\52\43\0\1\53\13\0\2\7\1\0\1\7\3\0"+
    "\1\7\1\52\1\54\3\0\1\54\52\0\2\7\1\55"+
    "\1\7\1\56\1\0\1\57\1\7\1\52\1\54\3\0"+
    "\1\54\13\0\1\57\36\0\10\11\1\0\11\11\3\0"+
    "\7\11\34\0\2\60\1\0\1\60\3\0\1\60\60\0"+
    "\10\11\1\0\2\11\1\61\6\11\3\0\7\11\34\0"+
    "\10\11\1\0\6\11\1\62\2\11\3\0\7\11\34\0"+
    "\10\11\1\0\11\11\3\0\1\11\1\63\3\11\1\64"+
    "\1\11\27\0\1\65\2\0\24\65\1\66\1\0\37\65"+
    "\1\67\2\0\25\67\1\0\1\70\36\67\5\0\10\11"+
    "\1\0\10\11\1\71\3\0\7\11\34\0\10\11\1\0"+
    "\2\11\1\72\6\11\3\0\7\11\34\0\10\11\1\0"+
    "\11\11\3\0\4\11\1\73\2\11\74\0\1\74\13\0"+
    "\1\75\54\0\1\76\12\0\1\77\67\0\1\100\13\0"+
    "\2\7\1\0\1\7\3\0\1\7\1\52\43\0\1\101"+
    "\67\0\1\102\1\0\1\103\65\0\1\104\2\0\1\105"+
    "\64\0\1\106\67\0\1\107\12\0\1\110\2\111\1\0"+
    "\1\111\3\0\1\111\45\0\1\110\13\0\1\112\1\0"+
    "\1\112\64\0\4\113\1\0\1\113\1\0\1\113\1\0"+
    "\1\113\3\0\3\113\13\0\1\113\35\0\1\114\1\0"+
    "\1\114\3\0\1\114\60\0\2\60\1\0\1\60\3\0"+
    "\1\60\1\0\1\54\3\0\1\54\52\0\10\11\1\0"+
    "\3\11\1\115\5\11\3\0\7\11\34\0\10\11\1\0"+
    "\7\11\1\116\1\11\3\0\7\11\34\0\10\11\1\0"+
    "\6\11\1\117\2\11\3\0\7\11\34\0\10\11\1\0"+
    "\11\11\3\0\6\11\1\120\34\0\10\11\1\0\11\11"+
    "\3\0\7\11\17\0\1\121\14\0\10\11\1\0\11\11"+
    "\3\0\3\11\1\122\3\11\110\0\1\123\67\0\1\124"+
    "\13\0\2\111\1\0\1\111\3\0\1\111\60\0\10\11"+
    "\1\0\4\11\1\125\4\11\3\0\7\11\34\0\10\11"+
    "\1\0\10\11\1\115\3\0\7\11\34\0\10\11\1\0"+
    "\11\11\3\0\2\11\1\126\4\11\66\0\1\127\35\0"+
    "\10\11\1\0\11\11\3\0\7\11\17\0\1\130\14\0"+
    "\10\11\1\0\11\11\3\0\3\11\1\131\3\11\65\0"+
    "\1\132\65\0\1\133\70\0\1\134\71\0\1\135\30\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2800];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\14\1\1\11\4\1\4\11\2\1\12\11"+
    "\6\1\1\0\1\11\4\0\5\1\1\0\1\1\1\0"+
    "\4\1\7\11\1\1\1\11\1\1\2\11\1\0\10\1"+
    "\1\0\1\1\2\11\2\1\2\0\1\1\2\0\2\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[93];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 198) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println("LEXER: error: " + yytext());
            } 
            // fall through
          case 54: break;
          case 2: 
            { System.out.print(yytext());
            } 
            // fall through
          case 55: break;
          case 3: 
            { System.out.println("LEXER: newline token:");
            } 
            // fall through
          case 56: break;
          case 4: 
            { 
            } 
            // fall through
          case 57: break;
          case 5: 
            { System.out.println("LEXER: binary substraction token: " + yytext()); return new Symbol(sym.SUBSTRACTION, yyline, yycolumn,
																							new String(yytext()));
            } 
            // fall through
          case 58: break;
          case 6: 
            { System.out.println("LEXER: int token: " + yytext()); return new Symbol(sym.INT, yyline, yycolumn, new Integer(yytext()));
            } 
            // fall through
          case 59: break;
          case 7: 
            { System.out.println("LEXER: id token: " + yytext()); return new Symbol(sym.ID, yyline, yycolumn, new String(yytext()));
            } 
            // fall through
          case 60: break;
          case 8: 
            { System.out.println("LEXER: dot: " + yytext());
     return new Symbol(sym.DOT, yyline, yycolumn, new String(yytext()));
            } 
            // fall through
          case 61: break;
          case 9: 
            { System.out.println("LEXER: bitwise and: " + yytext());
     return new Symbol(sym.BIT_AND, yyline, yycolumn, new String(yytext()));
            } 
            // fall through
          case 62: break;
          case 10: 
            { System.out.println("LEXER: bitwise or: " + yytext());
     return new Symbol(sym.BIT_OR, yyline, yycolumn, new String(yytext()));
            } 
            // fall through
          case 63: break;
          case 11: 
            { System.out.println("LEXER: bitwise xor: " + yytext());
     return new Symbol(sym.BIT_XOR, yyline, yycolumn, new String(yytext()));
            } 
            // fall through
          case 64: break;
          case 12: 
            { System.out.println("LEXER: bitwise inversion: " + yytext());
     return new Symbol(sym.BIT_INVERSION, yyline, yycolumn, new String(yytext()));
            } 
            // fall through
          case 65: break;
          case 13: 
            { System.out.println("LEXER: greater than token: " + yytext()); return new Symbol(sym.GT, yyline, yycolumn,
																				  new String(yytext()));
            } 
            // fall through
          case 66: break;
          case 14: 
            { System.out.println("LEXER: less than token: " + yytext()); return new Symbol(sym.LT, yyline, yycolumn,
																				  new String(yytext()));
            } 
            // fall through
          case 67: break;
          case 15: 
            { System.out.println("LEXER: left square bracket: " + yytext());
     return new Symbol(sym.LSQB, yyline, yycolumn, new String(yytext()));
            } 
            // fall through
          case 68: break;
          case 16: 
            { System.out.println("LEXER: right square bracket: " + yytext());
     return new Symbol(sym.RSQB, yyline, yycolumn, new String(yytext()));
            } 
            // fall through
          case 69: break;
          case 17: 
            { System.out.println("LEXER: left parenthesis: " + yytext());
     return new Symbol(sym.LPAR, yyline, yycolumn, new String(yytext()));
            } 
            // fall through
          case 70: break;
          case 18: 
            { System.out.println("LEXER: right parenthesis: " + yytext());
     return new Symbol(sym.RPAR, yyline, yycolumn, new String(yytext()));
            } 
            // fall through
          case 71: break;
          case 19: 
            { System.out.println("LEXER: left curly bracket: " + yytext());
     return new Symbol(sym.LBRACE, yyline, yycolumn, new String(yytext()));
            } 
            // fall through
          case 72: break;
          case 20: 
            { System.out.println("LEXER: right curly bracket: " + yytext());
     return new Symbol(sym.RBRACE, yyline, yycolumn, new String(yytext()));
            } 
            // fall through
          case 73: break;
          case 21: 
            { System.out.println("LEXER: comma: " + yytext());
     return new Symbol(sym.COMMA, yyline, yycolumn, new String(yytext()));
            } 
            // fall through
          case 74: break;
          case 22: 
            { System.out.println("LEXER: colon: " + yytext());
     return new Symbol(sym.COLON, yyline, yycolumn, new String(yytext()));
            } 
            // fall through
          case 75: break;
          case 23: 
            { System.out.println("LEXER: semicolon: " + yytext());
     return new Symbol(sym.SEMICOLON, yyline, yycolumn, new String(yytext()));
            } 
            // fall through
          case 76: break;
          case 24: 
            { ;
            } 
            // fall through
          case 77: break;
          case 25: 
            { System.out.println("LEXER: assisgnment token: " + yytext()); return new Symbol(sym.ASSIGNMENT, yyline, yycolumn, new String(yytext()));
            } 
            // fall through
          case 78: break;
          case 26: 
            { System.out.println("LEXER: binary addition token: " + yytext()); return new Symbol(sym.ADDITION, yyline, yycolumn, 
																						new String(yytext()));
            } 
            // fall through
          case 79: break;
          case 27: 
            { System.out.println("LEXER: binary multiplication token: " + yytext()); return new Symbol(sym.MULTIPLICATION, yyline, yycolumn,
																							  new String(yytext()));
            } 
            // fall through
          case 80: break;
          case 28: 
            { System.out.println("LEXER: binary float division token: " + yytext()); return new Symbol(sym.FLOATDIVISION, yyline, yycolumn,
																							  new String(yytext()));
            } 
            // fall through
          case 81: break;
          case 29: 
            { System.out.println("LEXER: binary modulo token: " + yytext()); return new Symbol(sym.MODULO, yyline, yycolumn,
																					  new String(yytext()));
            } 
            // fall through
          case 82: break;
          case 30: 
            { System.out.println("LEXER: short substraction token: " + yytext()); return new Symbol(sym.SHORTSUBSTRACTION, yyline, yycolumn,
																							new String(yytext()));
            } 
            // fall through
          case 83: break;
          case 31: 
            { System.out.println("LEXER: float token: " + yytext()); return new Symbol(sym.FLOAT, yyline, yycolumn, new Float(yytext()));
            } 
            // fall through
          case 84: break;
          case 32: 
            { System.out.println("LEXER: str token: " + yytext()); return new Symbol(sym.STR, yyline, yycolumn, new String(yytext()));
            } 
            // fall through
          case 85: break;
          case 33: 
            { System.out.println("LEXER: disjunction: " + yytext());
      return new Symbol(sym.DISJUNCTION, yyline, yycolumn, new String(yytext()));
            } 
            // fall through
          case 86: break;
          case 34: 
            { System.out.println("LEXER: bitwise right shift: " + yytext());
      return new Symbol(sym.RIGHT_SHIFT, yyline, yycolumn, new String(yytext()));
            } 
            // fall through
          case 87: break;
          case 35: 
            { System.out.println("LEXER: greater or equal token: " + yytext()); return new Symbol(sym.GE, yyline, yycolumn,
																				  new String(yytext()));
            } 
            // fall through
          case 88: break;
          case 36: 
            { System.out.println("LEXER: bitwise left shift: " + yytext());
      return new Symbol(sym.LEFT_SHIFT, yyline, yycolumn, new String(yytext()));
            } 
            // fall through
          case 89: break;
          case 37: 
            { System.out.println("LEXER: less or equal token: " + yytext()); return new Symbol(sym.LE, yyline, yycolumn,
																				  new String(yytext()));
            } 
            // fall through
          case 90: break;
          case 38: 
            { System.out.println("LEXER: equality token: " + yytext()); return new Symbol(sym.EQ, yyline, yycolumn,
																				  new String(yytext()));
            } 
            // fall through
          case 91: break;
          case 39: 
            { System.out.println("LEXER: short addition token: " + yytext()); return new Symbol(sym.SHORTADDITION, yyline, yycolumn,
																					new String(yytext()));
            } 
            // fall through
          case 92: break;
          case 40: 
            { System.out.println("LEXER: short multiplication token: " + yytext()); return new Symbol(sym.SHORTMULTIPLICATION, yyline, yycolumn,
																							new String(yytext()));
            } 
            // fall through
          case 93: break;
          case 41: 
            { System.out.println("LEXER: binary power token: " + yytext()); return new Symbol(sym.DEGREE, yyline, yycolumn,
																					  new String(yytext()));
            } 
            // fall through
          case 94: break;
          case 42: 
            { System.out.println("LEXER: short floatdivision token: " + yytext()); return new Symbol(sym.SHORTFLOATDIVISION, yyline, yycolumn,
																							new String(yytext()));
            } 
            // fall through
          case 95: break;
          case 43: 
            { System.out.println("LEXER: binary int division token: " + yytext()); return new Symbol(sym.INTDIVISION, yyline, yycolumn, 
																							 new String(yytext()));
            } 
            // fall through
          case 96: break;
          case 44: 
            { System.out.println("LEXER: short modulo token: " + yytext()); return new Symbol(sym.SHORTMODULO, yyline, yycolumn,
																					  new String(yytext()));
            } 
            // fall through
          case 97: break;
          case 45: 
            { System.out.println("LEXER: inequality token: " + yytext()); return new Symbol(sym.NE, yyline, yycolumn,
																				  new String(yytext()));
            } 
            // fall through
          case 98: break;
          case 46: 
            { System.out.println("LEXER: conjunction: " + yytext());
       return new Symbol(sym.CONJUNCTION, yyline, yycolumn, new String(yytext()));
            } 
            // fall through
          case 99: break;
          case 47: 
            { System.out.println("LEXER: negation: " + yytext());
       return new Symbol(sym.NEGATION, yyline, yycolumn, new String(yytext()));
            } 
            // fall through
          case 100: break;
          case 48: 
            { System.out.println("LEXER: short power token: " + yytext()); return new Symbol(sym.SHORTDEGREE, yyline, yycolumn,
																					  new String(yytext()));
            } 
            // fall through
          case 101: break;
          case 49: 
            { System.out.println("LEXER: short intdivision token: " + yytext()); return new Symbol(sym.SHORTINTDIVISION, yyline, yycolumn,
																							new String(yytext()));
            } 
            // fall through
          case 102: break;
          case 50: 
            { System.out.println("LEXER: bool token: " + yytext()); return new Symbol(sym.BOOL, yyline, yycolumn, new String(yytext()));
            } 
            // fall through
          case 103: break;
          case 51: 
            { System.out.println("LEXER: await: " + yytext());
         return new Symbol(sym.AWAIT, yyline, yycolumn, new String(yytext()));
            } 
            // fall through
          case 104: break;
          case 52: 
            { System.out.println("LEXER: identity: " + yytext());
          return new Symbol(sym.ISNOT, yyline, yycolumn, new String(yytext()));
            } 
            // fall through
          case 105: break;
          case 53: 
            { System.out.println("LEXER: membership: " + yytext());
          return new Symbol(sym.NOTIN, yyline, yycolumn, new String(yytext()));
            } 
            // fall through
          case 106: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java Lexer [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        Lexer scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new Lexer(reader);
          while ( !scanner.zzAtEOF ) scanner.next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
