
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SHORTADDITION = 15;
  public static final int SHORTINTDIVISION = 19;
  public static final int INT = 2;
  public static final int DEGREE = 14;
  public static final int SHORTSUBSTRACTION = 16;
  public static final int SHORTMULTIPLICATION = 17;
  public static final int FLOATDIVISION = 11;
  public static final int MODULO = 13;
  public static final int ID = 7;
  public static final int COMMA = 22;
  public static final int SHORTMODULO = 20;
  public static final int FLOAT = 3;
  public static final int EOF = 0;
  public static final int MULTIPLICATION = 10;
  public static final int SHORTFLOATDIVISION = 18;
  public static final int error = 1;
  public static final int SUBSTRACTION = 9;
  public static final int STR = 4;
  public static final int BOOL = 5;
  public static final int ASSIGNMENT = 6;
  public static final int SHORTDEGREE = 21;
  public static final int INTDIVISION = 12;
  public static final int ADDITION = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "FLOAT",
  "STR",
  "BOOL",
  "ASSIGNMENT",
  "ID",
  "ADDITION",
  "SUBSTRACTION",
  "MULTIPLICATION",
  "FLOATDIVISION",
  "INTDIVISION",
  "MODULO",
  "DEGREE",
  "SHORTADDITION",
  "SHORTSUBSTRACTION",
  "SHORTMULTIPLICATION",
  "SHORTFLOATDIVISION",
  "SHORTINTDIVISION",
  "SHORTMODULO",
  "SHORTDEGREE",
  "COMMA"
  };
}

