
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BIT_XOR = 8;
  public static final int SHORTMODULO = 44;
  public static final int SHORTADDITION = 39;
  public static final int SHORTDEGREE = 45;
  public static final int GE = 50;
  public static final int ASSIGNMENT = 30;
  public static final int STR = 28;
  public static final int BIT_AND = 6;
  public static final int SHORTFLOATDIVISION = 42;
  public static final int INT = 26;
  public static final int CONJUNCTION = 4;
  public static final int SUBSTRACTION = 33;
  public static final int SEMICOLON = 21;
  public static final int IS = 22;
  public static final int LT = 49;
  public static final int RPAR = 15;
  public static final int IN = 24;
  public static final int BOOL = 29;
  public static final int COMMA = 18;
  public static final int ISNOT = 23;
  public static final int DOT = 19;
  public static final int LSQB = 12;
  public static final int ID = 31;
  public static final int LE = 51;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int NEGATION = 5;
  public static final int LEFT_SHIFT = 11;
  public static final int DISJUNCTION = 3;
  public static final int MODULO = 37;
  public static final int DEGREE = 38;
  public static final int BIT_INVERSION = 9;
  public static final int EQ = 46;
  public static final int COLON = 20;
  public static final int AWAIT = 2;
  public static final int FLOATDIVISION = 35;
  public static final int NOTIN = 25;
  public static final int LBRACE = 16;
  public static final int NL = 52;
  public static final int RIGHT_SHIFT = 10;
  public static final int INTDIVISION = 36;
  public static final int ADDITION = 32;
  public static final int FLOAT = 27;
  public static final int RBRACE = 17;
  public static final int NE = 47;
  public static final int SHORTMULTIPLICATION = 41;
  public static final int LPAR = 14;
  public static final int BIT_OR = 7;
  public static final int RSQB = 13;
  public static final int SHORTINTDIVISION = 43;
  public static final int SHORTSUBSTRACTION = 40;
  public static final int GT = 48;
  public static final int MULTIPLICATION = 34;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "AWAIT",
  "DISJUNCTION",
  "CONJUNCTION",
  "NEGATION",
  "BIT_AND",
  "BIT_OR",
  "BIT_XOR",
  "BIT_INVERSION",
  "RIGHT_SHIFT",
  "LEFT_SHIFT",
  "LSQB",
  "RSQB",
  "LPAR",
  "RPAR",
  "LBRACE",
  "RBRACE",
  "COMMA",
  "DOT",
  "COLON",
  "SEMICOLON",
  "IS",
  "ISNOT",
  "IN",
  "NOTIN",
  "INT",
  "FLOAT",
  "STR",
  "BOOL",
  "ASSIGNMENT",
  "ID",
  "ADDITION",
  "SUBSTRACTION",
  "MULTIPLICATION",
  "FLOATDIVISION",
  "INTDIVISION",
  "MODULO",
  "DEGREE",
  "SHORTADDITION",
  "SHORTSUBSTRACTION",
  "SHORTMULTIPLICATION",
  "SHORTFLOATDIVISION",
  "SHORTINTDIVISION",
  "SHORTMODULO",
  "SHORTDEGREE",
  "EQ",
  "NE",
  "GT",
  "LT",
  "GE",
  "LE",
  "NL"
  };
}

